### ISSUE TITLE
0.4 tracker and cleanup

### ISSUE THREAD

**Issue by awestlake87** [awestlake87/sc2-rs#39]
### TODO before 0.4 release

- [x] Game Restarts in Melee coordinator
- [ ] Replay Observers
- [ ] Query interface
- [ ] Game Warnings and Errors?
- [x] Fix 'break on CTRL-C' feature (only used for wine).
- [ ] More examples
  - [ ] Replay
  - [ ] Intermediate Bot
- [ ] Reduce public API as much as possible
  - [x] Remove UpdateScheme
  - [x] Split Action-related structs into pub action submodule
  - [x] Split Debug-related structs into pub debug submodule
  - [ ] Split Query-related structs into pub query submodule
  - [x] Split Observer-related structs into pub observer submodule
  - [x] Split Melee-related structs into pub melee submodule
  - [x] Split Replay-related structs into pub replay submodule
- [ ] Update to futures 0.2
  - [x] Updated to futures-await 0.1.1
- [x] Split debug actions off into a separate client for replay observers.
- [x] Find a place to host documentation if docs.rs won't work.
- [x] Fix links in README.
- [x] Sensible errors.
- [x] Make sure Game Restarts actually work correctly. I'm not sure if my computer was just being sluggish or if there is actually an issue, but the second run seemed much slower when I tried it.
- [ ] Implement sample_creep and sample_visibility for Observation
- [x] Check that realtime works.
- [ ] Start using winepath to determine filepaths for maps and replays. 
- [ ] Update sc2_proto to 0.2
  - [ ] Check if sc2_proto builds in environments without protoc

### CLEANUP before 0.4 release

- [x] Reorganize the data structures for actions
- [x] Do actions need rc unit or just tag?
- [x] Builders
  - [x] Melee settings builder
  - [x] Launcher settings builder
  - [x] Agent builder
  - [x] Computer builder
- [x] ~~make organelle a feature and~~ use raw futures instead
- [x] Give data structures getters instead of pub fields?
  - [x] observation
  - [x] unit
- [x] Consistent capitalization of comments
- [x] Remove `super::` from root crate imports
- [ ] Add wrapper for any publicly exposed channels
  - [ ] Provide Into trait for demotion into raw channel
